### ISSUE TITLE
miss weapon type and character type

### ISSUE THREAD

**Issue by srwgin** [adangtran87/gbf-weap#14]
weapon type
cosmos

character type
attack defense heal balanced special

you can check 10. Cosmos Weapons
http://gbf-english.proboards.com/thread/595/weapon-summon-optimisation-progression

and some weapon has 2 attack skill
http://gbf.game-a.mbga.jp/assets/img_light/sp/assets/weapon/s/1040803600.jpg
Primary Skill Small Damage and Health
Secondary Skill Medium Damage

btw
is party_characters only consider  main not included sub

**Comment by adangtran87** [comment]
When creating tickets, please create a ticket that contains one issue at a time. For instance, this ticket should've been 4 tickets:

* Add support for Cosmos weapons
* Add character type descriptions
* Add support for two weapon skills
* Question about party_character limits

Putting them into one ticket with an ineffective title makes me have to go into the ticket to figure out what the ticket is about. Please do not close any tickets that are not implemented just because it is not implemented in a timely manner; I will close the ticket with a reason if I am not implementing it nor not within the scope of this project.

To address some items in this ticket:
* Cosmos weapons are not currently supported but could be added in the future
* Character types do not have any affect on weapon optimization to my knowledge
* Two weapon skill supports (or really a list of weapon_skills) could be added in the future
* Technically party_characters contain no limits; you could pick 20 characters and it'll find the best weapon pool that gives the best cumulative damage for all 20 characters (assuming they were in the same party at the same time). In practical terms, you would probably not want to specify more than 5 characters to find the best weapon pool that supports all 5. This could mean that pools with bahamut weapons could be devalued since you're balancing the cost across all 5 characters. Other ways to think about it is that you could only specify 'important' characters where you want to maximize pool damage (aka only attackers) as the value of the buffer/utility characters are in the buffs instead of raw damage.

I'm going to close this ticket since it is an ineffective ticket. Create new effective tickets if you wish for a specific feature to be implemented.
